export const SeekerConstants = {
    BASE_LINK: './',
    CHANNEL_LINK: './channel',
    FAVS_LINK: './favorites',
    FAVS_KEY: 'favorites',
    CHANNEL_KEY: 'channel',
};
export const SeekerTexts = {
    ADVANCE_TIME: 'Advance 10 seconds',
    RETURN_TIME: 'Return 10 seconds',
    CHANNEL: 'Channel',
    CLOSED: 'Closed',
    COLLAPSE: 'Collapse',
    UNCOLLAPSE: 'Uncollapse',
    FAVS_LIST: 'Favorites list',
    FAVS: 'Favorites',
    FETCHING_ERROR: 'Error fetching',
    INPUT_SEARCH_PLACEHOLDER: 'National Geographic, midudev...',
    LAST_CHANNEL: 'Last Channel',
    LAST_SEARCH: 'Last Search',
    MENU: 'Menu',
    MUTE: 'Mute',
    UNMUTE: 'Unmute',
    NEW_SEARCH: 'Make a new search',
    NO_FAVS: 'You still have no favorite saved',
    OPEN: 'Open',
    PLAY: 'Play',
    PAUSE: 'Pause',
    PODCAST_SEARCH_ENGINE: 'Podcast search engine',
    SEARCH_RESULTS: 'Search results',
    SEEK: 'Seek',
    SORRY: 'Sorry about that! The channel has not been loaded',
    VOLUME_REGULATOR_DISPLAY: 'Display volume regulator',
    WATCH: 'Watch'
};